default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_laiblitz_a_development

test:
  <<: *default
  database: furima_laiblitz_a_test


production:
  <<: *default
  database: furima_laiblitz_a_production
  username: furima_laiblitz_a
  password: <%= ENV["FURIMA_LAIBLITZ_A_DATABASE_PASSWORD"] %>
